#   PHP Dependencies builder

FROM composer:2.1.5 as vendor

WORKDIR /builder

COPY database/ database/
COPY ["composer.json","composer.lock","./"]

#RUN composer install
RUN composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist \
    --optimize-autoloader --no-dev

#
#   APPLICATION
#

FROM php:8.1.16-fpm-alpine3.17

WORKDIR /var/www

COPY --from=vendor /builder/vendor/ ./vendor/

# Install the system's dependencies.
RUN apk update && apk add --no-cache \
    libpng \
    libpng-dev \
    libzip-dev \
    libtool \
    build-base \
    make \
    autoconf && \
    pecl install redis \
    && docker-php-ext-enable redis && \
    docker-php-ext-install pdo_mysql exif pcntl bcmath gd zip 

RUN pecl channel-update pecl.php.net

COPY docker/nginx/default.conf /etc/nginx/conf.d/

# Create system's user
RUN adduser --disabled-password -u 1000 -h /home/php php \
    && addgroup php www-data \
    && addgroup php root

COPY . .

# Only for testing purposes
COPY .env.example .env

RUN chown -R php:www-data public/ storage/ bootstrap/cache/ && \
    chmod -R 0777  storage/ bootstrap/cache/ public/

RUN php artisan config:cache
RUN php artisan route:cache

EXPOSE 9000

CMD ["php-fpm", "-F", "-R"]